version: "3.8"

services:
  spark-master:
    container_name: spark-master
    image: open-dataplatform-spark
    build:
      context: .
    ports:
      - 8080:8080
    command:
      - master
    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    volumes:
      - ./example/scripts:/scripts
      - ./scripts:/opt/spark/scripts

  spark-worker-1:
    container_name: spark-worker-1
    image: open-dataplatform-spark
    build:
      context: .
    ports:
      - 8081:8081
    command:
      - worker
    environment:
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_MASTER_URL: spark-master:7077

networks:
  default:
    external:
      name: dataplatform_default
