version: "3.8"

services:
  trino:
    image: trinodb/trino:353
    container_name: trino
    ports:
      - 8089:8080
    volumes:
      - ./config/catalog:/etc/trino/catalog
      - ./config/jvm.config:/etc/trino/jvm.config
      - ./config/config.properties:/etc/trino/config.properties

  sqlpad:
    image: sqlpad/sqlpad:latest
    ports:
      - "3000:3000"
    environment:
      SQLPAD_CONNECTIONS__datawarehouse__name: Data Warehouse
      SQLPAD_CONNECTIONS__datawarehouse__driver: trino
      SQLPAD_CONNECTIONS__datawarehouse__host: trino
      SQLPAD_CONNECTIONS__datawarehouse__username: sqlpad
      SQLPAD_CONNECTIONS__datawarehouse__catalog: hive
      SQLPAD_AUTH_DISABLED: "true"
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: "admin"
    volumes:
      - seed-data:/etc/sqlpad/seed-data

networks:
  default:
    external:
      name: dataplatform-network

volumes:
  seed-data:
