version: "3.8"

services:
  namenode:
    image: open-dataplatform-hadoop
    container_name: namenode
    build:
      context: .
    volumes:
      - datanode_vol:/hadoop/hdfs/name
      - ./config:/etc/hadoop
    command:
      - hdfs
      - namenode
    environment:
      IS_MASTER: "1"
    ports:
      - 50070:50070

  datanode:
    image: open-dataplatform-hadoop
    container_name: datanode
    build:
      context: .
    volumes:
      - datanode_vol:/hadoop/hdfs/data
      - ./config:/etc/hadoop
    command:
      - hdfs
      - datanode
    ports:
      - 50075:50075
volumes:
  datanode_vol:
  namenode_vol:

networks:
  default:
    name: dataplatform-network
