version: "3.8"

services:
  namenode:
    image: open-dataplatform-hdfs:latest
    container_name: namenode
    build:
      context: .
    volumes:
      - datanode_vol:/dfs
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command:
      - namenode
    environment:
      - HDFS_NAMENODE_URL=hdfs://namenode:8020
    ports:
      - 50070:50070

  datanode:
    image: open-dataplatform-hdfs:latest
    container_name: datanode
    build:
      context: .
    environment:
      - HDFS_NAMENODE_URL=hdfs://namenode:8020
    volumes:
      - datanode_vol:/dfs
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command:
      - datanode
    ports:
      - 50075:50075
volumes:
  datanode_vol:
  namenode_vol:

networks:
  default:
    name: dataplatform_default
