version: "3.8"

services:
  postgres:
    image: postgres:9.4
    container_name: hive-postgres
    ports:
      - 5433:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
      - ./scripts/hive-schema-3.1.0.postgres.sql:/docker-entrypoint-initdb.d/hive-schema-3.1.0.postgres.sql
    environment:
      POSTGRES_PASSWORD: hive
      POSTGRES_USER: hive
      POSTGRES_DB: metastore

  hive:
    build: .
    image: open-dataplatform-hive
    container_name: hive
    command:
      - hiveserver2
    depends_on:
      - hive-metastore
    volumes:
      - ./config:/opt/hive/conf
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      SERVICE_PRECONDITION: "hive-metastore:9083"

  hive-metastore:
    build: .
    image: open-dataplatform-hive
    container_name: hive-metastore
    command: hive --service metastore
    depends_on:
      - postgres
    volumes:
      - ./config:/opt/hive/conf
    ports:
      - 9083:9083
    environment:
      SERVICE_PRECONDITION: "postgres:5432 namenode:50070 datanode:50075"

  hue:
    image: gethue/hue:latest
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ./config/hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - "db"

  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./sql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hue
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

networks:
  default:
    external:
      name: dataplatform-network
